const baseReactions = {
    cat: { emoji: '🐱', soundText: 'meow meow!', animation: 'animate-bounce', overlay: 'smile' },
    dog: { emoji: '🐶', soundText: 'woof woof!', animation: 'animate-bounce', overlay: 'bark' },
    lion: { emoji: '🦁', soundText: 'roaaaar!', animation: 'animate-extreme-shake', overlay: 'roar' },
    tiger: { emoji: '🐯', soundText: 'roaaaar!', animation: 'animate-extreme-shake', overlay: 'roar', overlayClass: 'bottom-[12%] w-[65%] h-[40%]' },
    bear: { emoji: '🐻', soundText: 'grrrrrr!', animation: 'animate-extreme-shake', overlay: 'roar', overlayClass: 'bottom-[10%] w-[55%] h-[40%]' },
    wolf: { emoji: '🐺', soundText: 'awooooo!', animation: 'animate-pulse', overlay: 'bark' },
    fox: { emoji: '🦊', soundText: 'yip yip!', animation: 'animate-bounce', overlay: 'bark' },
    cow: { emoji: '🐮', soundText: 'moooo!', animation: 'animate-pulse', overlay: 'bark' },
    pig: { emoji: '🐷', soundText: 'oink oink!', animation: 'animate-extreme-shake', overlay: 'bark' },
    sheep: { emoji: '🐑', soundText: 'baaaa!', animation: 'animate-pulse', overlay: 'bark' },
    horse: { emoji: '🐴', soundText: 'neigh!', animation: 'animate-extreme-shake', overlay: 'roar' },
    monkey: { emoji: '🐵', soundText: 'ooh ooh ah ah!', animation: 'animate-bounce', overlay: 'smile' },
    gorilla: { emoji: '🦍', soundText: 'ooh ooh!', animation: 'animate-extreme-shake', overlay: 'roar' },
    elephant: { emoji: '🐘', soundText: 'pawoo!', animation: 'animate-pulse', overlay: 'bark' },
    rhino: { emoji: '🦏', soundText: 'snort!', animation: 'animate-extreme-shake', overlay: 'roar' },
    hippo: { emoji: '🦛', soundText: 'splash!', animation: 'animate-pulse', overlay: 'roar' },
    mouse: { emoji: '🐭', soundText: 'squeak!', animation: 'animate-pulse', overlay: 'smile' },
    rat: { emoji: '🐀', soundText: 'squeak!', animation: 'animate-pulse', overlay: 'smile' },
    rabbit: { emoji: '🐰', soundText: 'thump thump!', animation: 'animate-bounce', overlay: 'smile' },
    bat: { emoji: '🦇', soundText: 'screech!', animation: 'animate-extreme-shake', overlay: 'roar' },
    koala: { emoji: '🐨', soundText: 'munch munch!', animation: 'animate-bounce', overlay: 'smile' },
    panda: { emoji: '🐼', soundText: 'munch munch!', animation: 'animate-bounce', overlay: 'smile' },
    sloth: { emoji: '🦥', soundText: 'yawn...', animation: 'animate-pulse', overlay: 'smile' },
    camel: { emoji: '🐪', soundText: 'grunt!', animation: 'animate-pulse', overlay: 'bark' },
    giraffe: { emoji: '🦒', soundText: 'munch!', animation: 'animate-bounce', overlay: 'smile' },

    bird: { emoji: '🐦', soundText: 'tweet tweet!', animation: 'animate-bounce', overlay: 'smile' },
    eagle: { emoji: '🦅', soundText: 'cawww!', animation: 'animate-extreme-shake', overlay: 'roar' },
    owl: { emoji: '🦉', soundText: 'hoot hoot!', animation: 'animate-pulse', overlay: 'shock' },
    penguin: { emoji: '🐧', soundText: 'waddle waddle!', animation: 'animate-bounce', overlay: 'smile' },
    chicken: { emoji: '🐔', soundText: 'cluck cluck!', animation: 'animate-extreme-shake', overlay: 'bark' },
    duck: { emoji: '🦆', soundText: 'quack quack!', animation: 'animate-bounce', overlay: 'bark' },
    turkey: { emoji: '🦃', soundText: 'gobble gobble!', animation: 'animate-extreme-shake', overlay: 'bark' },
    parrot: { emoji: '🦜', soundText: 'squawk!', animation: 'animate-bounce', overlay: 'smile' },
    peacock: { emoji: '🦚', soundText: 'squawk!', animation: 'animate-pulse', overlay: 'smile' },
    swan: { emoji: '🦢', soundText: 'honk!', animation: 'animate-bounce', overlay: 'smile' },
    flamingo: { emoji: '🦩', soundText: 'honk!', animation: 'animate-bounce', overlay: 'smile' },
    dove: { emoji: '🕊️', soundText: 'coo!', animation: 'animate-pulse', overlay: 'smile' },

    fish: { emoji: '🐟', soundText: 'blub blub!', animation: 'animate-bounce', overlay: 'shock' },
    shark: { emoji: '🦈', soundText: 'chomp!', animation: 'animate-extreme-shake', overlay: 'roar' },
    whale: { emoji: '🐳', soundText: 'wooooosh!', animation: 'animate-pulse', overlay: 'smile' },
    dolphin: { emoji: '🐬', soundText: 'eee eee!', animation: 'animate-bounce', overlay: 'smile' },
    octopus: { emoji: '🐙', soundText: 'squish!', animation: 'animate-pulse', overlay: 'shock' },
    squid: { emoji: '🦑', soundText: 'squish!', animation: 'animate-pulse', overlay: 'shock' },
    crab: { emoji: '🦀', soundText: 'snip snip!', animation: 'animate-extreme-shake', overlay: 'smile' },
    lobster: { emoji: '🦞', soundText: 'snip snip!', animation: 'animate-extreme-shake', overlay: 'smile' },
    seal: { emoji: '🦭', soundText: 'arf arf!', animation: 'animate-bounce', overlay: 'bark' },

    snake: { emoji: '🐍', soundText: 'hsssss!', animation: 'animate-extreme-shake', overlay: 'roar' },
    turtle: { emoji: '🐢', soundText: 'slow and steady!', animation: 'animate-pulse', overlay: 'smile' },
    crocodile: { emoji: '🐊', soundText: 'snap!', animation: 'animate-extreme-shake', overlay: 'roar' },
    alligator: { emoji: '🐊', soundText: 'snap!', animation: 'animate-extreme-shake', overlay: 'roar' },
    frog: { emoji: '🐸', soundText: 'ribbit!', animation: 'animate-bounce', overlay: 'smile' },
    toad: { emoji: '🐸', soundText: 'croak!', animation: 'animate-bounce', overlay: 'smile' },
    lizard: { emoji: '🦎', soundText: 'scurry!', animation: 'animate-pulse', overlay: 'smile' },
    dinosaur: { emoji: '🦖', soundText: 'ROAAR!', animation: 'animate-extreme-shake', overlay: 'roar' },
    dragon: { emoji: '🐉', soundText: 'ROAAR!', animation: 'animate-extreme-shake', overlay: 'roar' },

    bug: { emoji: '🐛', soundText: 'crawl...', animation: 'animate-bounce', overlay: 'smile' },
    butterfly: { emoji: '🦋', soundText: 'flutter!', animation: 'animate-pulse', overlay: 'smile' },
    bee: { emoji: '🐝', soundText: 'bzzzz!', animation: 'animate-extreme-shake', overlay: 'smile' },
    ant: { emoji: '🐜', soundText: 'march!', animation: 'animate-bounce', overlay: 'smile' },
    spider: { emoji: '🕷️', soundText: 'creep...', animation: 'animate-extreme-shake', overlay: 'shock' },
    ladybug: { emoji: '🐞', soundText: 'fly away!', animation: 'animate-bounce', overlay: 'smile' },
    beetle: { emoji: '🪲', soundText: 'buzz!', animation: 'animate-pulse', overlay: 'smile' },
    caterpillar: { emoji: '🐛', soundText: 'munch!', animation: 'animate-bounce', overlay: 'smile' },

    apple: { emoji: '🍎', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    banana: { emoji: '🍌', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    orange: { emoji: '🍊', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    grape: { emoji: '🍇', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    mango: { emoji: '🥭', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    watermelon: { emoji: '🍉', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    strawberry: { emoji: '🍓', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    peach: { emoji: '🍑', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    pomegranate: { src: '/images/pomegranate.png', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    pear: { emoji: '🍐', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    cherry: { emoji: '🍒', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    lemon: { emoji: '🍋', soundText: 'Sour!', animation: 'animate-extreme-shake', overlay: 'shock' },
    kiwi: { emoji: '🥝', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    pineapple: { emoji: '🍍', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'cool' },

    carrot: { emoji: '🥕', soundText: 'Crunch!', animation: 'animate-bounce', overlay: 'smile' },
    potato: { emoji: '🥔', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    tomato: { emoji: '🍅', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    corn: { emoji: '🌽', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    broccoli: { emoji: '🥦', soundText: 'Healthy!', animation: 'animate-bounce', overlay: 'smile' },
    onion: { emoji: '🧅', soundText: 'Spicy!', animation: 'animate-extreme-shake', overlay: 'shock' },
    garlic: { emoji: '🧄', soundText: 'Pungent!', animation: 'animate-pulse', overlay: 'smile' },
    ginger: { emoji: '🫚', soundText: 'Spicy!', animation: 'animate-pulse', overlay: 'smile' },
    mushroom: { emoji: '🍄', soundText: 'Magic!', animation: 'animate-bounce', overlay: 'smile' },
    cabbage: { emoji: '🥬', soundText: 'Crunchy!', animation: 'animate-bounce', overlay: 'smile' },
    radish: { emoji: '🧅', soundText: 'Spicy crunch!', animation: 'animate-bounce', overlay: 'smile' },
    eggplant: { emoji: '🍆', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    cauliflower: { emoji: '🧄', soundText: 'Healthy white florets!', animation: 'animate-bounce', overlay: 'smile' },
    cucumber: { emoji: '🥒', soundText: 'Fresh!', animation: 'animate-bounce', overlay: 'smile' },
    pumpkin: { emoji: '🎃', soundText: 'Spooky!', animation: 'animate-extreme-shake', overlay: 'smile' },
    sweet_potato: { emoji: '🍠', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    bell_pepper: { emoji: '🫑', soundText: 'Crunch!', animation: 'animate-bounce', overlay: 'smile' },
    hot_pepper: { emoji: '🌶️', soundText: 'Hot!', animation: 'animate-extreme-shake', overlay: 'shock' },
    pea_pod: { emoji: '🫛', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    salad: { emoji: '🥗', soundText: 'Healthy!', animation: 'animate-bounce', overlay: 'smile' },
    melon_green: { emoji: '🍈', soundText: 'Fresh!', animation: 'animate-bounce', overlay: 'smile' },


    rose: { emoji: '🌹', soundText: 'Beautiful!', animation: 'animate-pulse', overlay: 'smile' },
    sunflower: { emoji: '🌻', soundText: 'Sunny!', animation: 'animate-bounce', overlay: 'smile' },
    tulip: { emoji: '🌷', soundText: 'Beautiful!', animation: 'animate-pulse', overlay: 'smile' },
    daisy: { emoji: '🌼', soundText: 'Pretty!', animation: 'animate-bounce', overlay: 'smile' },
    lotus: { emoji: '🪷', soundText: 'Peaceful!', animation: 'animate-pulse', overlay: 'smile' },
    lily: { emoji: '💮', soundText: 'Beautiful!', animation: 'animate-pulse', overlay: 'smile' },
    oleander: { emoji: '🌺', soundText: 'Beautiful!', animation: 'animate-pulse', overlay: 'smile' },
    marigold: { emoji: '🏵️', soundText: 'Bright!', animation: 'animate-bounce', overlay: 'smile' },
    jasmine: { emoji: '💮', soundText: 'Fragrant!', animation: 'animate-pulse', overlay: 'smile' },
    plumeria: { emoji: '🌼', soundText: 'Beautiful!', animation: 'animate-pulse', overlay: 'smile' },
    lavender: { emoji: '🪻', soundText: 'Relaxing!', animation: 'animate-pulse', overlay: 'smile' },
    cherry_blossom: { emoji: '🌸', soundText: 'Beautiful!', animation: 'animate-pulse', overlay: 'smile' },
    tree: { emoji: '🌳', soundText: 'Nature!', animation: 'animate-bounce', overlay: 'smile' },
    cactus: { emoji: '🌵', soundText: 'Ouch!', animation: 'animate-extreme-shake', overlay: 'shock' },
    fern: { emoji: '🌿', soundText: 'Fresh!', animation: 'animate-pulse', overlay: 'smile' },
    leaf: { emoji: '🍃', soundText: 'Swoosh!', animation: 'animate-bounce', overlay: 'smile' },

    sun: { emoji: '☀️', soundText: 'Too cool!', animation: 'animate-pulse', overlay: 'cool' },
    moon: { emoji: '🌙', soundText: 'Nighttime!', animation: 'animate-pulse', overlay: 'cool' },
    star: { emoji: '⭐', soundText: 'Shining bright!', animation: 'animate-pulse', overlay: 'cool' },
    cloud: { emoji: '☁️', soundText: 'Fluffy!', animation: 'animate-bounce', overlay: 'smile' },
    rain: { emoji: '🌧️', soundText: 'Splish splash!', animation: 'animate-pulse', overlay: 'shock' },
    snow: { emoji: '❄️', soundText: 'Brrrr!', animation: 'animate-extreme-shake', overlay: 'shock' },
    lightning: { emoji: '⚡', soundText: 'Zap!', animation: 'animate-extreme-shake', overlay: 'shock' },
    rainbow: { emoji: '🌈', soundText: 'Magical!', animation: 'animate-pulse', overlay: 'smile' },
    tornado: { emoji: '🌪️', soundText: 'Whoosh!', animation: 'animate-extreme-shake', overlay: 'shock' },

    car: { emoji: '🚗', soundText: 'Vroom vroom!', animation: 'animate-extreme-shake', overlay: 'cool' },
    bus: { emoji: '🚌', soundText: 'Beep beep!', animation: 'animate-bounce', overlay: 'cool' },
    train: { emoji: '🚂', soundText: 'Choo choo!', animation: 'animate-extreme-shake', overlay: 'smile' },
    boat: { emoji: '⛵', soundText: 'Ahoy!', animation: 'animate-bounce', overlay: 'smile' },
    ship: { emoji: '🚢', soundText: 'Honk honk!', animation: 'animate-extreme-shake', overlay: 'roar' },
    plane: { emoji: '✈️', soundText: 'Whoosh!', animation: 'animate-bounce', overlay: 'cool' },
    helicopter: { emoji: '🚁', soundText: 'Chop chop!', animation: 'animate-extreme-shake', overlay: 'cool' },
    bicycle: { emoji: '🚲', soundText: 'Ring ring!', animation: 'animate-bounce', overlay: 'smile' },
    rocket: { emoji: '🚀', soundText: 'Blast off!', animation: 'animate-extreme-shake', overlay: 'shock' },

    pizza: { emoji: '🍕', soundText: 'Pizza time!', animation: 'animate-bounce', overlay: 'smile' },
    burger: { emoji: '🍔', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    cake: { emoji: '🎂', soundText: 'Delicious!', animation: 'animate-bounce', overlay: 'smile' },
    bread: { emoji: '🍞', soundText: 'Tasty!', animation: 'animate-bounce', overlay: 'smile' },
    cheese: { emoji: '🧀', soundText: 'Cheesy!', animation: 'animate-bounce', overlay: 'smile' },
    egg: { emoji: '🥚', soundText: 'Crack!', animation: 'animate-bounce', overlay: 'shock' },
    milk: { emoji: '🥛', soundText: 'Glug glug!', animation: 'animate-bounce', overlay: 'smile' },
    coffee: { emoji: '☕', soundText: 'Hot!', animation: 'animate-pulse', overlay: 'smile' },
    tea: { emoji: '🍵', soundText: 'Sip...', animation: 'animate-pulse', overlay: 'smile' },
    taco: { emoji: '🌮', soundText: 'Crunch!', animation: 'animate-extreme-shake', overlay: 'smile' },
    sushi: { emoji: '🍣', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },

    ghost: { emoji: '👻', soundText: 'Booooo!', animation: 'animate-extreme-shake', overlay: 'shock' },
    alien: { emoji: '👽', soundText: 'We come in peace!', animation: 'animate-extreme-shake', overlay: 'shock' },
    robot: { emoji: '🤖', soundText: 'Beep boop!', animation: 'animate-pulse', overlay: 'shock' },
    book: { emoji: '📚', soundText: 'Reading is fun!', animation: 'animate-bounce', overlay: 'smile' },
    ball: { emoji: '⚽', soundText: 'Goal!', animation: 'animate-bounce', overlay: 'smile' },
    pencil: { emoji: '✏️', soundText: 'Scribble!', animation: 'animate-bounce', overlay: 'smile' },
    phone: { emoji: '📱', soundText: 'Ring ring!', animation: 'animate-extreme-shake', overlay: 'smile' },
    computer: { emoji: '💻', soundText: 'Click clack!', animation: 'animate-bounce', overlay: 'cool' },
    clock: { emoji: '🕒', soundText: 'Tick tock!', animation: 'animate-bounce', overlay: 'shock' },
    key: { emoji: '🔑', soundText: 'Click!', animation: 'animate-bounce', overlay: 'smile' },
    lock: { emoji: '🔒', soundText: 'Locked!', animation: 'animate-pulse', overlay: 'shock' },
    sword: { emoji: '⚔️', soundText: 'Clang!', animation: 'animate-extreme-shake', overlay: 'shock' },
    shield: { emoji: '🛡️', soundText: 'Defend!', animation: 'animate-pulse', overlay: 'cool' },
    gem: { emoji: '💎', soundText: 'Shiny!', animation: 'animate-pulse', overlay: 'cool' },
    crown: { emoji: '👑', soundText: 'Royal!', animation: 'animate-bounce', overlay: 'cool' },
    
    temple: { emoji: '🛕', soundText: 'Peaceful!', animation: 'animate-pulse', overlay: 'smile' },
    church: { emoji: '⛪', soundText: 'Peaceful!', animation: 'animate-pulse', overlay: 'smile' },
    mosque: { emoji: '🕌', soundText: 'Peaceful!', animation: 'animate-pulse', overlay: 'smile' },
    school: { emoji: '🏫', soundText: 'Learning!', animation: 'animate-bounce', overlay: 'smile' },
    house: { emoji: '🏠', soundText: 'Home sweet home!', animation: 'animate-bounce', overlay: 'smile' },
    hospital: { emoji: '🏥', soundText: 'Healing!', animation: 'animate-pulse', overlay: 'smile' },
    
    // Body Parts
    hand: { emoji: '✋', soundText: 'High five!', animation: 'animate-bounce', overlay: 'smile' },
    palm: { emoji: '🖐️', soundText: 'High five!', animation: 'animate-bounce', overlay: 'smile' },
    nail: { emoji: '💅', soundText: 'Pretty!', animation: 'animate-pulse', overlay: 'smile' },
    finger: { emoji: '☝️', soundText: 'Point!', animation: 'animate-bounce', overlay: 'smile' },
    head: { emoji: '👤', soundText: 'Think!', animation: 'animate-pulse', overlay: 'smile' },
    hair: { emoji: '💇', soundText: 'Style!', animation: 'animate-pulse', overlay: 'smile' },
    toe: { emoji: '🦶', soundText: 'Wiggle!', animation: 'animate-bounce', overlay: 'smile' },
    foot: { emoji: '🦶', soundText: 'Step!', animation: 'animate-bounce', overlay: 'smile' },
    lip: { emoji: '👄', soundText: 'Smile!', animation: 'animate-bounce', overlay: 'smile' },
    cheek: { emoji: '😊', soundText: 'Smile!', animation: 'animate-bounce', overlay: 'smile' },
    skin: { emoji: '🤚', soundText: 'Soft!', animation: 'animate-pulse', overlay: 'smile' },
    neck: { emoji: '🧣', soundText: 'Warm!', animation: 'animate-pulse', overlay: 'smile' },
    back: { emoji: '🔙', soundText: 'Back!', animation: 'animate-pulse', overlay: 'smile' },
    leg: { emoji: '🦵', soundText: 'Walk!', animation: 'animate-bounce', overlay: 'smile' },
    arm: { emoji: '💪', soundText: 'Strong!', animation: 'animate-extreme-shake', overlay: 'cool' },
    eye: { emoji: '👁️', soundText: 'See!', animation: 'animate-pulse', overlay: 'shock' },
    ear: { emoji: '👂', soundText: 'Hear!', animation: 'animate-pulse', overlay: 'smile' },
    nose: { emoji: '👃', soundText: 'Sniff!', animation: 'animate-bounce', overlay: 'smile' },
    mouth: { emoji: '👄', soundText: 'Speak!', animation: 'animate-pulse', overlay: 'smile' },
    tooth: { emoji: '🦷', soundText: 'Bite!', animation: 'animate-bounce', overlay: 'smile' },
    tongue: { emoji: '👅', soundText: 'Taste!', animation: 'animate-bounce', overlay: 'smile' },
    bone: { emoji: '🦴', soundText: 'Crunch!', animation: 'animate-bounce', overlay: 'shock' },
    blood: { emoji: '🩸', soundText: 'Drop!', animation: 'animate-pulse', overlay: 'shock' },
    brain: { emoji: '🧠', soundText: 'Smart!', animation: 'animate-pulse', overlay: 'cool' },
    heart: { emoji: '❤️', soundText: 'Love!', animation: 'animate-pulse', overlay: 'smile' },
    lung: { emoji: '🫁', soundText: 'Breathe!', animation: 'animate-pulse', overlay: 'smile' },
    
    moustache: { emoji: '🧔', soundText: 'Stylish!', animation: 'animate-bounce', overlay: 'smile' },
    forehead: { emoji: '👤', soundText: 'Big brain!', animation: 'animate-pulse', overlay: 'smile' },
    knee: { emoji: '🦵', soundText: 'Bend!', animation: 'animate-bounce', overlay: 'smile' },
    thigh: { emoji: '🦵', soundText: 'Strong!', animation: 'animate-pulse', overlay: 'smile' },
    ankle: { emoji: '🦶', soundText: 'Step!', animation: 'animate-bounce', overlay: 'smile' },
    heel: { emoji: '🦶', soundText: 'Tap!', animation: 'animate-pulse', overlay: 'smile' },
    buttock: { emoji: '🍑', soundText: 'Sit!', animation: 'animate-bounce', overlay: 'smile' },
    gut: { emoji: '🤰', soundText: 'Full!', animation: 'animate-bounce', overlay: 'smile' },
    
    // Misc Foods, Animals, Plants
    litchi: { src: '/images/lychee.png', soundText: 'Sweet!', animation: 'animate-bounce', overlay: 'smile' },
    sugarcane: { emoji: '🎋', soundText: 'Sweet!', animation: 'animate-pulse', overlay: 'smile' },
    sugar: { emoji: '🧂', soundText: 'Sweet!', animation: 'animate-pulse', overlay: 'smile' },
    mongoose: { emoji: '🦦', soundText: 'Quick!', animation: 'animate-bounce', overlay: 'smile' },
    oriole: { emoji: '🐦', soundText: 'Tweet!', animation: 'animate-bounce', overlay: 'smile' },
    nut: { emoji: '🥜', soundText: 'Crunchy!', animation: 'animate-pulse', overlay: 'smile' },
    fig: { src: '/images/fig.png', soundText: 'Sweet!', animation: 'animate-bounce', overlay: 'smile' },
    raisin: { src: '/images/raisin.png', soundText: 'Sweet!', animation: 'animate-bounce', overlay: 'smile' },
    tamarind: { emoji: '🫘', soundText: 'Tangy!', animation: 'animate-extreme-shake', overlay: 'shock' },
    nutmeg: { emoji: '🌰', soundText: 'Spicy!', animation: 'animate-pulse', overlay: 'smile' },
    ice: { emoji: '🧊', soundText: 'Cold!', animation: 'animate-extreme-shake', overlay: 'shock' },
    honey: { emoji: '🍯', soundText: 'Sweet!', animation: 'animate-bounce', overlay: 'smile' },
    wood_apple: { emoji: '🥥', soundText: 'Hard!', animation: 'animate-bounce', overlay: 'smile' },
    clove: { src: '/images/clove.png', soundText: 'Spicy!', animation: 'animate-pulse', overlay: 'smile' },
    cardamom: { src: '/images/cardamom.png', soundText: 'Aromatic!', animation: 'animate-pulse', overlay: 'smile' },
    cumin: { emoji: '🌱', soundText: 'Earthy!', animation: 'animate-pulse', overlay: 'smile' },
};

// Map hundreds of aliases to the base reactions
export const REACTIONS = {
    ...baseReactions,
    // Domestic / Farm
    kitty: baseReactions.cat,
    kitten: baseReactions.cat,
    feline: baseReactions.cat,
    puppy: baseReactions.dog,
    pup: baseReactions.dog,
    hound: baseReactions.dog,
    calf: baseReactions.cow,
    bull: baseReactions.cow,
    ox: baseReactions.cow,
    hog: baseReactions.pig,
    sow: baseReactions.pig,
    piglet: baseReactions.pig,
    ram: baseReactions.sheep,
    ewe: baseReactions.sheep,
    lamb: baseReactions.sheep,
    foal: baseReactions.horse,
    pony: baseReactions.horse,
    mare: baseReactions.horse,
    stallion: baseReactions.horse,
    hen: baseReactions.chicken,
    cock: baseReactions.chicken,
    rooster: baseReactions.chicken,
    chick: baseReactions.chicken,
    // Wild Mammals
    cub: baseReactions.bear, // generic cub
    ape: baseReactions.gorilla,
    chimp: baseReactions.monkey,
    chimpanzee: baseReactions.monkey,
    deer: { emoji: '🦌', soundText: 'prance!', animation: 'animate-bounce', overlay: 'smile' },
    buck: { emoji: '🦌', soundText: 'prance!', animation: 'animate-bounce', overlay: 'smile' },
    doe: { emoji: '🦌', soundText: 'prance!', animation: 'animate-bounce', overlay: 'smile' },
    fawn: { emoji: '🦌', soundText: 'prance!', animation: 'animate-bounce', overlay: 'smile' },
    puma: baseReactions.lion,
    cougar: baseReactions.lion,
    panther: baseReactions.tiger,
    leopard: baseReactions.tiger,
    cheetah: baseReactions.tiger,
    jaguar: baseReactions.tiger,
    // Birds
    pigeon: baseReactions.dove,
    crow: { emoji: '🐦‍⬛', soundText: 'caw!', animation: 'animate-bounce', overlay: 'bark' },
    raven: { emoji: '🐦‍⬛', soundText: 'caw!', animation: 'animate-bounce', overlay: 'bark' },
    hawk: baseReactions.eagle,
    falcon: baseReactions.eagle,
    ostrich: { emoji: '🦤', soundText: 'squawk!', animation: 'animate-extreme-shake', overlay: 'shock' },
    // Aquatic
    goldfish: baseReactions.fish,
    guppy: baseReactions.fish,
    eel: { emoji: '🐍', soundText: 'zap!', animation: 'animate-pulse', overlay: 'shock' },
    stingray: baseReactions.fish,
    ray: baseReactions.fish,
    // Reptiles
    gecko: baseReactions.lizard,
    iguana: baseReactions.lizard,
    chameleon: baseReactions.lizard,
    // Bugs
    fly: baseReactions.bug,
    mosquito: baseReactions.bug,
    wasp: baseReactions.bee,
    hornet: baseReactions.bee,
    roach: baseReactions.bug,
    cockroach: baseReactions.bug,
    // Flowers / Plants
    orchid: baseReactions.tulip,
    vine: baseReactions.fern,
    bush: baseReactions.tree,
    shrub: baseReactions.tree,
    pine: baseReactions.tree,
    // Fruits
    plum: baseReactions.peach,
    berry: baseReactions.strawberry,
    melon: baseReactions.watermelon,
    citrus: baseReactions.orange,
    // Vehicles
    auto: baseReactions.car,
    taxi: baseReactions.car,
    cab: baseReactions.car,
    truck: { emoji: '🚚', soundText: 'Honk honk!', animation: 'animate-bounce', overlay: 'cool' },
    van: { emoji: '🚐', soundText: 'Beep beep!', animation: 'animate-bounce', overlay: 'cool' },
    jet: baseReactions.plane,
    // Foods
    candy: { emoji: '🍬', soundText: 'Sweet!', animation: 'animate-bounce', overlay: 'smile' },
    chocolate: { emoji: '🍫', soundText: 'Sweet!', animation: 'animate-bounce', overlay: 'smile' },
    cookie: { emoji: '🍪', soundText: 'Crunch!', animation: 'animate-bounce', overlay: 'smile' },
    donut: { emoji: '🍩', soundText: 'Yummy!', animation: 'animate-bounce', overlay: 'smile' },
    'ice cream': { emoji: '🍦', soundText: 'Cold!', animation: 'animate-bounce', overlay: 'smile' },
    'hot dog': baseReactions.burger,
    'polar bear': baseReactions.bear,
    // Royalty
    king: baseReactions.crown,
    queen: baseReactions.crown,
    prince: baseReactions.crown,
    princess: baseReactions.crown,
    // Custom Additions
    'king fisher': baseReactions.bird,
    'kingfisher': baseReactions.bird,
    'robin bird': baseReactions.bird,
    'robin': baseReactions.bird,
    'wood pecker': baseReactions.bird,
    'woodpecker': baseReactions.bird,
    'heron': baseReactions.bird,
    'crane': baseReactions.bird,
    'cauli flower': baseReactions.cauliflower,
    'cauliflower': baseReactions.cauliflower,
    'cabbage': baseReactions.cabbage,
    'radish': baseReactions.radish,
    'brinjal': baseReactions.eggplant,
    'eggplant': baseReactions.eggplant,
    'sparrow': baseReactions.bird,
    'cuckoo': baseReactions.bird,
    'tube rose': baseReactions.lily,
    'tuberose': baseReactions.lily,
    'water lily': baseReactions.lotus,
    'waterlily': baseReactions.lotus,
    'lotus': baseReactions.lotus,
    'lily': baseReactions.lily,
    'oleander': baseReactions.oleander,
    'champa': baseReactions.plumeria,
    'mogra': baseReactions.jasmine,
    'jasmine': baseReactions.jasmine,
    'marigold': baseReactions.marigold,
    'lavender': baseReactions.lavender,
    'peony': baseReactions.cherry_blossom,
    'dahlia': baseReactions.marigold,
    'chrysanthemum': baseReactions.daisy,
    'magnolia': baseReactions.lily,
    'camellia': baseReactions.oleander,
    'poppy': baseReactions.rose,
    'zinnia': baseReactions.marigold,
    'petunia': baseReactions.cherry_blossom,
    'carnation': baseReactions.oleander,
    'spinach': baseReactions.cabbage,
    'lettuce': baseReactions.salad,
    'cucumber': baseReactions.cucumber,
    'pumpkin': baseReactions.pumpkin,
    'beetroot': baseReactions.sweet_potato,
    'turnip': baseReactions.potato,
    'capsicum': baseReactions.bell_pepper,
    'bell pepper': baseReactions.bell_pepper,
    'green chilli': baseReactions.bell_pepper,
    'red chilli': baseReactions.hot_pepper,
    'okra': baseReactions.cucumber,
    'ladys finger': baseReactions.cucumber,
    'lady finger': baseReactions.cucumber,
    'peas': baseReactions.pea_pod,
    'french beans': baseReactions.pea_pod,
    'cluster beans': baseReactions.pea_pod,
    'bitter gourd': baseReactions.cucumber,
    'bottle gourd': baseReactions.pear,
    'ridge gourd': baseReactions.cucumber,
    'sponge gourd': baseReactions.cucumber,
    'snake gourd': baseReactions.cucumber,
    'ash gourd': baseReactions.melon_green,
    'ivy gourd': baseReactions.cucumber,
    'drumstick': baseReactions.fern,
    'temple': baseReactions.temple,
    'church': baseReactions.church,
    'mosque': baseReactions.mosque,
    'school': baseReactions.school,
    'house': baseReactions.house,
    'home': baseReactions.house,
    'hospital': baseReactions.hospital,
    
    // Body Parts
    'hand': baseReactions.hand,
    'hands': baseReactions.hand,
    'palm': baseReactions.palm,
    'palms': baseReactions.palm,
    'nail': baseReactions.nail,
    'nails': baseReactions.nail,
    'finger': baseReactions.finger,
    'fingers': baseReactions.finger,
    'head': baseReactions.head,
    'heads': baseReactions.head,
    'hair': baseReactions.hair,
    'hairs': baseReactions.hair,
    'toe': baseReactions.toe,
    'toes': baseReactions.toe,
    'foot': baseReactions.foot,
    'feet': baseReactions.foot,
    'lip': baseReactions.lip,
    'lips': baseReactions.lip,
    'cheek': baseReactions.cheek,
    'cheeks': baseReactions.cheek,
    'skin': baseReactions.skin,
    'neck': baseReactions.neck,
    'necks': baseReactions.neck,
    'back': baseReactions.back,
    'beck': baseReactions.back, // Adding beck as alias since user mentioned it
    'leg': baseReactions.leg,
    'legs': baseReactions.leg,
    'arm': baseReactions.arm,
    'arms': baseReactions.arm,
    'eye': baseReactions.eye,
    'eyes': baseReactions.eye,
    'ear': baseReactions.ear,
    'ears': baseReactions.ear,
    'nose': baseReactions.nose,
    'mouth': baseReactions.mouth,
    'tooth': baseReactions.tooth,
    'teeth': baseReactions.tooth,
    'tongue': baseReactions.tongue,
    'bone': baseReactions.bone,
    'bones': baseReactions.bone,
    'blood': baseReactions.blood,
    'brain': baseReactions.brain,
    'heart': baseReactions.heart,
    'lung': baseReactions.lung,
    'lungs': baseReactions.lung,
    'beak': baseReactions.bird, // Just in case beck was meant as beak
    
    'moustache': baseReactions.moustache,
    'mustache': baseReactions.moustache,
    'moustaches': baseReactions.moustache,
    'forehead': baseReactions.forehead,
    'foreheads': baseReactions.forehead,
    'knee': baseReactions.knee,
    'knees': baseReactions.knee,
    'thigh': baseReactions.thigh,
    'thighs': baseReactions.thigh,
    'ankle': baseReactions.ankle,
    'ankles': baseReactions.ankle,
    'heel': baseReactions.heel,
    'heels': baseReactions.heel,
    'buttock': baseReactions.buttock,
    'buttocks': baseReactions.buttock,
    'gut': baseReactions.gut,
    'guts': baseReactions.gut,
    
    'litchi': baseReactions.litchi,
    'lychee': baseReactions.litchi,
    'sugarcane': baseReactions.sugarcane,
    'sugar cane': baseReactions.sugarcane,
    'star apple': baseReactions.melon_green,
    'water apple': baseReactions.apple,
    'sugar': baseReactions.sugar,
    'mongoose': baseReactions.mongoose,
    'oriole': baseReactions.oriole,
    'cashew': baseReactions.nut,
    'cashews': baseReactions.nut,
    'pistachio': baseReactions.nut,
    'pistachios': baseReactions.nut,
    'fig': baseReactions.fig,
    'figs': baseReactions.fig,
    'raisin': baseReactions.raisin,
    'raisins': baseReactions.raisin,
    'turmeric': baseReactions.ginger,
    'tamarind': baseReactions.tamarind,
    'shaddock': baseReactions.melon_green,
    'wood apple': baseReactions.wood_apple,
    'nutmeg': baseReactions.nutmeg,
    'pepper': baseReactions.hot_pepper,
    'peppers': baseReactions.hot_pepper,
    'mint': baseReactions.leaf,
    'ice': baseReactions.ice,
    'honey': baseReactions.honey,
    'clove': baseReactions.clove,
    'cloves': baseReactions.clove,
    'cardamom': baseReactions.cardamom,
    'cumin': baseReactions.cumin,
};
